

avial:
	g++ -g avialTree.cpp traverse.cpp

tree:
	g++ -g tree.cpp stack.cpp 
convert:
	g++ -g treetoarray.cpp
artotr:
	g++ -g convertArrayToTree.cpp traverse.cpp
pree:
	g++ -g preordertotree.cpp traverse.cpp

removal:
	g++ -g removalOfNode.cpp traverse.cpp
clean:
	rm -rf a.out
